name: Enterprise DevSecOps Pipeline

on:
  push:
    branches:
      - master

jobs:
  devsecops-pipeline:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Make Detection Script Executable
        run: chmod +x scripts/detect-tech.sh

      - name: Detect Application Technologies
        run: ./scripts/detect-tech.sh

      - name: Display Detected Technologies
        run: |
          echo "NODE=$NODE"
          echo "PYTHON=$PYTHON"
          echo "JAVA=$JAVA"
          echo "DOCKER=$DOCKER"
          echo "TERRAFORM=$TERRAFORM"
          echo "K8S=$K8S"

      - name: Setup Node.js
        if: env.NODE == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Node.js Dependencies
        if: env.NODE == 'true'
        run: npm install

      - name: Build Docker Image
        if: env.DOCKER == 'true'
        run: |
          docker build -t fitness-tracker:${{ github.sha }} .

      - name: Verify Kubernetes Manifests
        if: env.K8S == 'true'
        run: |
          ls k8s/

      - name: Pipeline Completed
        run: echo "Enterprise dynamic pipeline executed successfully"